### ISSUE TITLE
Php 8.1 Compability

### ISSUE THREAD

**Issue by gokhanakdag** [phpro/phpro-mage2-module-translations#10]
Package phpro/mage2-module-translations has requirements incompatible with your PHP version, PHP extensions and Composer version:  
    - phpro/mage2-module-translations 0.1.1 requires php ^7.1 which does not match your installed version 8.1.2.

**Comment by stefliekens** [comment]
Hi @gokhanakdag, thanks for using our module. You should at least upgrade to [version 1.2.0](https://github.com/phpro/phpro-mage2-module-translations/releases/tag/1.2.0) which has compatibility for PHP 7.4 and 8.1.

**Comment by gokhanakdag** [comment]
Please try to install it via composer. It doenst work.

**Comment by stefliekens** [comment]
hi @gokhanakdag , but I can see you are using an old version (0.1.1) of the module. Probably you need to update the version in your composer.json file first.

**Comment by gokhanakdag** [comment]
Please try installing it vith a fresh magento 2 via composer command : composer require phpro/mage2-module-translations.
And then see what happens.
