### ISSUE TITLE
Module breaks Magento Setup Install

### ISSUE THREAD

**Issue by bartlubbersen** [phpro/phpro-mage2-module-translations#19]
First of all thank you for this module!

Currently the module seems to break the default Magento setup:install. This is because in the construct of the command `GenerateFrontendTranslations` it depends on `InlineTranslationsGenerator`. That class however depends on `Magento\Store\Model\System\Store` which uses the StoreManager and initializes the stores/websites and so forth.

During setup install these stores/websites are not created yet when the console construct is executed.
This issue can be resolved quite easily by using a Proxy for the class in the console command or the generator.

Unfortunately I don't have time right now to create a PR, maybe later, but at least wanted to share so it can be fixed and others might be helped.

**Comment by BrentRobert** [comment]
Hi @bartlubbersen,
Thank you for notifying us of the problem!
After having a quick look it seems there's more than 1 command relying on classes that should be proxied.

We'll create a new release soon rectifying these issues.

**Comment by BrentRobert** [comment]
Hi @bartlubbersen,
I just released version 1.5.0 of the module.
Let me know if this doesn't rectify the issue for you!
